### ISSUE TITLE
Mutual exclusive  constraints

### ISSUE THREAD

**Issue by Pamasi** [EGiunchiglia/ROAD-R#1]
Hi, 
I saw that the number of constraints listed in [requirements_readable.txt](https://github.com/EGiunchiglia/ROAD-R/blob/main/requirements/requirements_readable.txt) is higher than the one present in the paper. In particular, I do not understand the constraint _Ped not Xing Car Cyc Mobike MedVeh LarVeh Bus EmVeh_, which should mean that only _Ped, Car, Cyc, Mobike, MedVeh, LarVeh, Bus, EmVeh_ could perform the action _Xing_ if I follow the overall logic expressed in the paper for similar constraints (Ped not XingFmLft Car Cyc Mobike MedVeh LarVeh Bus EmVeh), but later there are other constraints that state the Car, Cyc, Mobike,  MedVeh, LarVeh, Bus, EmVeh cannot cross, which are _not Car not Xing_, _not Mobike not Xing_, _not MedVeh not Xing_, _not LarVeh not Xing_, _not Bus not Xing_, _not EmVeh not Xing_ .

**Comment by EGiunchiglia** [comment]
Yes you are right, we are sorry for this lapse. We will double check both the constraints listed in the paper and those listed in this repo. For now, please ignore the constraint _Ped not Xing Car Cyc Mobike MedVeh LarVeh Bus EmVeh_ as later on there is also the constraint _Ped Cyc not Xing_. Hope this helped.

**Comment by Pamasi** [comment]
Hi, thanks for the clarification!
